# This is a part of the Minecraft server configuration.
# Only a few settings are listed here. You can add more settings to the file.
# For the full list of settings or more information, please refer to the Minecraft wiki.
# https://minecraft.wiki/w/Server.properties

level-name=world
level-seed=-8013592586951995800 

gamemode=survival
difficulty=normal
hardcore=false

max-players=10
max-world-size=29999984
spawn-protection=0

allow-flight=false
enable-command-block=false
generate-structures=true